version: 2
jobs:
  build:
    docker:
     
      - image: circleci/node:7.10
    working_directory: ~/repo

    steps:
      -checkout 
      -run: cd ./client npm run build && aws s3 sync build/ s3://serverless-graphql-demo
